#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-hbc
Version  : 2.2.0
Release  : 1
URL      : https://github.com/twitter/hbc/archive/hbc-2.2.0.tar.gz
Source0  : https://github.com/twitter/hbc/archive/hbc-2.2.0.tar.gz
Source1  : https://repo1.maven.org/maven2/com/twitter/hbc-core/2.2.0/hbc-core-2.2.0.jar
Source2  : https://repo1.maven.org/maven2/com/twitter/hbc-core/2.2.0/hbc-core-2.2.0.pom
Source3  : https://repo1.maven.org/maven2/com/twitter/hbc/2.2.0/hbc-2.2.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-hbc-data = %{version}-%{release}
Requires: mvn-hbc-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
# Hosebird Client (hbc) [![Build Status](https://travis-ci.org/twitter/hbc.png?branch=master)](https://travis-ci.org/twitter/hbc) [![Coverage Status](https://coveralls.io/repos/twitter/hbc/badge.png?branch=master)](https://coveralls.io/r/twitter/hbc?branch=master)
A Java HTTP client for consuming Twitter's [Streaming API](https://dev.twitter.com/docs/streaming-apis)

%package data
Summary: data components for the mvn-hbc package.
Group: Data

%description data
data components for the mvn-hbc package.


%package license
Summary: license components for the mvn-hbc package.
Group: Default

%description license
license components for the mvn-hbc package.


%prep
%setup -q -n hbc-hbc-2.2.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-hbc
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-hbc/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/twitter/hbc-core/2.2.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/twitter/hbc-core/2.2.0/hbc-core-2.2.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/twitter/hbc-core/2.2.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/twitter/hbc-core/2.2.0/hbc-core-2.2.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/twitter/hbc/2.2.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/twitter/hbc/2.2.0/hbc-2.2.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/twitter/hbc-core/2.2.0/hbc-core-2.2.0.jar
/usr/share/java/.m2/repository/com/twitter/hbc-core/2.2.0/hbc-core-2.2.0.pom
/usr/share/java/.m2/repository/com/twitter/hbc/2.2.0/hbc-2.2.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-hbc/LICENSE
